DELETE FROM presidents;

INSERT INTO presidents (number, name, first_name, last_name, nickname, term_start, term_end, party, home_state, birth_year, death_year, birth_place, vice_presidents, historian_ranking, era, tagline, famous_quote, key_achievements, defining_moment, did_you_know) VALUES
(1,'George Washington','George','Washington','Father of His Country',1789,1797,'Unaffiliated','Virginia',1732,1799,'Pope''s Creek, Virginia',ARRAY['John Adams'],2,'founding','First in war. First in peace. He set the standard — then walked away.','To be prepared for war is one of the most effective means of preserving peace.',ARRAY['Led the Continental Army to victory in the Revolutionary War','Presided over the Constitutional Convention of 1787','Established the two-term presidential precedent','Created the Cabinet system of executive government','Signed the Residence Act establishing the nation''s capital'],'Voluntarily relinquishing power after two terms, establishing the democratic norm of peaceful transfer of power.','His famous wooden teeth are a myth. His dentures were crafted from ivory, human teeth, and animal teeth set in lead.'),
(2,'John Adams','John','Adams','Atlas of Independence',1797,1801,'Federalist','Massachusetts',1735,1826,'Braintree, Massachusetts',ARRAY['Thomas Jefferson'],19,'founding','The forgotten founder. Kept the peace when war was popular.','Facts are stubborn things.',ARRAY['Kept the United States out of war with France','Established the Navy Department','Signed the Treaty of Mortefontaine','Appointed John Marshall as Chief Justice','Moved into the newly completed White House'],'Resisting public pressure for war with France, negotiating peace through the XYZ Affair at great political cost to himself.','Adams and Jefferson both died on July 4, 1826 — exactly 50 years after the Declaration of Independence.'),
(3,'Thomas Jefferson','Thomas','Jefferson','Man of the People',1801,1809,'Democratic-Republican','Virginia',1743,1826,'Shadwell, Virginia',ARRAY['Aaron Burr','George Clinton'],7,'founding','Philosopher. Architect. President. Hypocrite. Revolutionary.','We hold these truths to be self-evident, that all men are created equal.',ARRAY['Authored the Declaration of Independence','Completed the Louisiana Purchase doubling the nation''s size','Commissioned the Lewis and Clark Expedition','Founded the University of Virginia','Abolished the international slave trade'],'The Louisiana Purchase in 1803, acquiring 828,000 square miles from Napoleon for $15 million.','Jefferson was a prolific inventor and is credited with popularizing macaroni and cheese in America after bringing a pasta machine back from France.'),
(4,'James Madison','James','Madison','Father of the Constitution',1809,1817,'Democratic-Republican','Virginia',1751,1836,'Port Conway, Virginia',ARRAY['George Clinton','Elbridge Gerry'],17,'founding','Wrote the rules. Then had to govern by them.','If men were angels, no government would be necessary.',ARRAY['Primary architect of the U.S. Constitution','Co-authored the Federalist Papers','Steered the nation through the War of 1812','Signed the charter for the Second Bank of the United States','Oversaw the burning and rebuilding of Washington DC'],'The burning of Washington DC by British forces in 1814, forcing Madison to flee the White House.','Madison was the shortest U.S. president at 5 feet 4 inches and weighed around 100 pounds.'),
(5,'James Monroe','James','Monroe','The Last Founding Father',1817,1825,'Democratic-Republican','Virginia',1758,1831,'Westmoreland County, Virginia',ARRAY['Daniel D. Tompkins'],13,'founding','The Era of Good Feelings. One party. One vision. One America.','The American continents are henceforth not to be considered as subjects for future colonization by any European powers.',ARRAY['Proclaimed the Monroe Doctrine','Oversaw the acquisition of Florida from Spain','Presided over the Era of Good Feelings','Signed the Missouri Compromise','Won re-election with virtually no opposition in 1820'],'The Monroe Doctrine of 1823, declaring the Western Hemisphere off-limits to European colonization.','Monroe was the last president to wear a powdered wig. He won re-election in 1820 with 231 of 232 electoral votes.'),
(6,'John Quincy Adams','John Quincy','Adams','Old Man Eloquent',1825,1829,'Democratic-Republican','Massachusetts',1767,1848,'Braintree, Massachusetts',ARRAY['John C. Calhoun'],21,'founding','Won the presidency. Lost the people. Won history.','If your actions inspire others to dream more, learn more, do more and become more, you are a leader.',ARRAY['Promoted a national university and astronomical observatory','Expanded roads and canals infrastructure','Negotiated treaties expanding U.S. territory','Served as a congressman after the presidency opposing slavery','Argued the Amistad case before the Supreme Court'],'His return to Congress after the presidency, using that platform to fight slavery for 17 years until his death at his desk.','Adams loved to skinny dip in the Potomac River every morning at 5am.'),
(7,'Andrew Jackson','Andrew','Jackson','Old Hickory',1829,1837,'Democrat','Tennessee',1767,1845,'Waxhaws, South Carolina',ARRAY['John C. Calhoun','Martin Van Buren'],18,'antebellum','The people''s president. Hero to millions. Villain to thousands.','One man with courage makes a majority.',ARRAY['Expanded presidential power and executive authority','Defeated the Second Bank of the United States','Survived the first presidential assassination attempt','Forced the Cherokee removal on the Trail of Tears','Preserved the Union during the Nullification Crisis'],'The forced removal of Native Americans via the Indian Removal Act, resulting in the Trail of Tears.','Jackson carried two bullets in his body for most of his presidency from duels and frontier fights.'),
(8,'Martin Van Buren','Martin','Van Buren','Old Kinderhook',1837,1841,'Democrat','New York',1782,1862,'Kinderhook, New York',ARRAY['Richard Mentor Johnson'],34,'antebellum','Built the party machine. Got crushed by the economy.','It is easier to do a job right than to explain why you didn''t.',ARRAY['Established the independent treasury system','Founded the Democratic Party organizational structure','First president born a U.S. citizen','Maintained neutrality during Canadian rebellions','Created the principle of executive privilege'],'Inheriting and mishandling the Panic of 1837, one of the worst economic depressions in American history.','The slang term "OK" may derive from his nickname Old Kinderhook used in his 1840 campaign.'),
(9,'William Henry Harrison','William Henry','Harrison','Tippecanoe',1841,1841,'Whig','Ohio',1773,1841,'Charles City County, Virginia',ARRAY['John Tyler'],NULL,'antebellum','32 days. The shortest presidency in history.','The only legitimate right to govern is an express grant of power from the governed.',ARRAY['Won the presidency with the first modern campaign using slogans and songs','Delivered the longest inaugural address in history at 8445 words','Died 31 days into office from pneumonia','Established precedent of vice presidential succession','Grandfather of President Benjamin Harrison'],'Dying of pneumonia on April 4, 1841, just 31 days after his inauguration — the shortest presidency in American history.','Harrison gave the longest inaugural address in history in cold wet weather without a hat or coat. He died 31 days later.'),
(10,'John Tyler','John','Tyler','His Accidency',1841,1845,'Whig','Virginia',1790,1862,'Charles City County, Virginia',ARRAY['None'],NULL,'antebellum','Nobody''s president. Everybody''s problem.','I can never consent to being dictated to.',ARRAY['Established the precedent of full presidential succession','Annexed Texas setting the stage for westward expansion','Signed the Preemption Act allowing settlers to claim frontier land','Negotiated the Webster-Ashburton Treaty','Opened trade relations with China via Treaty of Wangxia'],'Asserting full presidential powers after Harrison''s death, refusing to be called Acting President.','Tyler was expelled from the Whig Party while president, making him the only president with no party affiliation while in office.');

INSERT INTO presidents (number, name, first_name, last_name, nickname, term_start, term_end, party, home_state, birth_year, death_year, birth_place, vice_presidents, historian_ranking, era, tagline, famous_quote, key_achievements, defining_moment, did_you_know) VALUES
(11,'James K. Polk','James','Polk','Young Hickory',1845,1849,'Democrat','Tennessee',1795,1849,'Pineville, North Carolina',ARRAY['George M. Dallas'],11,'antebellum','Said he''d do four things. Did all four. Went home.','No president who performs his duties faithfully and conscientiously can have any leisure.',ARRAY['Acquired California and the Southwest via the Mexican-American War','Settled the Oregon boundary dispute with Britain','Established the independent treasury','Reduced tariffs through the Walker Tariff','Served exactly one term as promised and retired'],'The Mexican-American War and the Treaty of Guadalupe Hidalgo, acquiring over 500,000 square miles including California.','Polk set four goals at the start of his presidency, achieved all four, and died just 103 days after leaving office.'),
(12,'Zachary Taylor','Zachary','Taylor','Old Rough and Ready',1849,1850,'Whig','Louisiana',1784,1850,'Barboursville, Virginia',ARRAY['Millard Fillmore'],NULL,'antebellum','War hero president. Died before the war he might have prevented.','I have always done my duty. I am ready to die. My only regret is for the friends I leave behind.',ARRAY['Navigated California statehood debate','Resisted Southern threats of secession','Proposed the Clayton-Bulwer Treaty with Britain','Brought military credibility to the presidency','Died 16 months into office'],'His unexpected death on July 9, 1850, removing a Southern slaveholder who had vowed to personally lead troops against secessionists.','Taylor never voted in a presidential election before winning one, as he moved too often as a military officer to establish permanent residence.'),
(13,'Millard Fillmore','Millard','Fillmore','The American Louis Philippe',1850,1853,'Whig','New York',1800,1874,'Summerhill, New York',ARRAY['None'],NULL,'antebellum','Signed the Compromise. Delayed the war. Doomed himself.','An honorable defeat is better than a dishonorable victory.',ARRAY['Signed the Compromise of 1850 including the Fugitive Slave Act','Opened Japan to American trade via Commodore Perry','Completed the Capitol dome construction funding','Established the White House library','Supported the transcontinental railroad survey'],'Signing the Fugitive Slave Act as part of the Compromise of 1850, which temporarily preserved the Union but outraged Northerners.','Fillmore founded the University of Buffalo and reportedly refused an honorary degree from Oxford, saying it would be absurd to have a degree conferred in Latin on someone who could not read Latin.'),
(14,'Franklin Pierce','Franklin','Pierce','Handsome Frank',1853,1857,'Democrat','New Hampshire',1804,1869,'Hillsborough, New Hampshire',ARRAY['William Rufus DeVane King'],40,'antebellum','Charming. Weak. Watched the country fracture.','The storm of frenzy and faction must inevitably dash itself in vain against the unshaken rock of the Constitution.',ARRAY['Signed the Kansas-Nebraska Act repealing the Missouri Compromise','Negotiated the Gadsden Purchase from Mexico','Opened trade with Japan','Expanded the U.S. military','Attempted to purchase Cuba from Spain'],'Signing the Kansas-Nebraska Act in 1854, which unleashed Bleeding Kansas and accelerated the nation toward Civil War.','Pierce witnessed his 11-year-old son Bennie killed in a train accident just two months before his inauguration.'),
(15,'James Buchanan','James','Buchanan','Old Buck',1857,1861,'Democrat','Pennsylvania',1791,1868,'Cove Gap, Pennsylvania',ARRAY['John C. Breckinridge'],44,'antebellum','The last president before the storm. Did nothing to stop it.','I like the noise of democracy.',ARRAY['Managed the Dred Scott decision fallout','Maintained formal neutrality as Southern states seceded','Handled the Panic of 1857','Negotiated several international trade treaties','Was the only president to remain a bachelor'],'Watching seven states secede during his final months and doing virtually nothing to stop it, handing Lincoln a nation already dissolving.','Buchanan is the only U.S. president who never married. His niece Harriet Lane served as White House hostess.'),
(16,'Abraham Lincoln','Abraham','Lincoln','Honest Abe',1861,1865,'Republican','Illinois',1809,1865,'Hardin County, Kentucky',ARRAY['Hannibal Hamlin','Andrew Johnson'],1,'civil_war','Saved the Union. Freed the enslaved. Paid with his life.','Government of the people, by the people, for the people, shall not perish from the earth.',ARRAY['Preserved the Union through the Civil War','Issued the Emancipation Proclamation','Delivered the Gettysburg Address','Signed the Homestead Act and Morrill Act','Established Thanksgiving as a national holiday'],'The Emancipation Proclamation of January 1, 1863, transforming the Civil War into a moral crusade against slavery.','Lincoln was the tallest president at 6 feet 4 inches and is the only president inducted into the Wrestling Hall of Fame.'),
(17,'Andrew Johnson','Andrew','Johnson','King Andy',1865,1869,'Democrat','Tennessee',1808,1875,'Raleigh, North Carolina',ARRAY['None'],23,'civil_war','Inherited Lincoln''s war. Betrayed Lincoln''s peace.','Honest conviction is my courage; the Constitution is my guide.',ARRAY['Oversaw the end of the Civil War','Purchased Alaska from Russia for $7.2 million','Became the first president to be impeached','Vetoed Reconstruction legislation repeatedly','Granted amnesty to Confederate soldiers'],'His impeachment by the House of Representatives in 1868, becoming the first U.S. president impeached — acquitted by the Senate by just one vote.','Johnson was almost entirely self-taught and could not read until his teens. He was taught to read by his wife Eliza.'),
(18,'Ulysses S. Grant','Ulysses','Grant','Unconditional Surrender Grant',1869,1877,'Republican','Ohio',1822,1885,'Point Pleasant, Ohio',ARRAY['Schuyler Colfax','Henry Wilson'],20,'civil_war','Won the war as general. Lost the peace as president.','I know only two tunes: one of them is Yankee Doodle and the other isn''t.',ARRAY['Ratified the 15th Amendment granting Black men the vote','Established Yellowstone as the first national park','Fought the Ku Klux Klan using the Enforcement Acts','Created the Department of Justice','Negotiated the Treaty of Washington with Britain'],'Signing the Ku Klux Klan Act of 1871 and deploying federal troops against white supremacist terrorism in the South.','Grant was a terrible student at West Point except in horsemanship, where he set a jumping record that stood for decades.'),
(19,'Rutherford B. Hayes','Rutherford','Hayes','His Fraudulency',1877,1881,'Republican','Ohio',1822,1893,'Delaware, Ohio',ARRAY['William A. Wheeler'],33,'gilded_age','Won the most disputed election in history. Then kept his promise to leave.','He serves his party best who serves his country best.',ARRAY['Ended Reconstruction by withdrawing federal troops from the South','Reformed the civil service system','Restored public confidence after Grant-era corruption','Vetoed the Bland-Allison Act limiting silver coinage','Served exactly one term as promised'],'The Compromise of 1877, settling the disputed 1876 election but effectively abandoning Black Americans in the South.','Hayes was the first president to use a telephone in the White House, installed personally by Alexander Graham Bell.'),
(20,'James A. Garfield','James','Garfield','Preacher President',1881,1881,'Republican','Ohio',1831,1881,'Orange Township, Ohio',ARRAY['Chester A. Arthur'],NULL,'gilded_age','Shot in July. Died in September. Killed by his doctors.','A brave man is a man who dares to look the Devil in the face and tell him he is the Devil.',ARRAY['Fought for civil service reform','Elevated Black representation in government appointments','Exposed the Star Route postal fraud','Proved the Pythagorean theorem in a new way','Was the last president born in a log cabin'],'Being shot by Charles Guiteau and dying 79 days later — not from the bullet but from infections caused by doctors probing his wound with unwashed fingers.','Garfield could write Latin with one hand and Greek with the other simultaneously.');

INSERT INTO presidents (number, name, first_name, last_name, nickname, term_start, term_end, party, home_state, birth_year, death_year, birth_place, vice_presidents, historian_ranking, era, tagline, famous_quote, key_achievements, defining_moment, did_you_know) VALUES
(21,'Chester A. Arthur','Chester','Arthur','Elegant Arthur',1881,1885,'Republican','Vermont',1829,1886,'Fairfield, Vermont',ARRAY['None'],32,'gilded_age','Machine politician turned reformer. Nobody saw it coming.','Men may die, but the fabrics of our free institutions remain unshaken.',ARRAY['Signed the Pendleton Civil Service Reform Act','Modernized and rebuilt the U.S. Navy','Signed the Chinese Exclusion Act','Oversaw renovation of the White House','Vetoed the Rivers and Harbors Act pork barrel bill'],'Signing the Pendleton Act in 1883, establishing merit-based civil service and destroying the spoils system that had made him.','Arthur owned 80 pairs of pants and changed clothes multiple times a day. He had the White House renovated by designer Louis Comfort Tiffany.'),
(22,'Grover Cleveland','Grover','Cleveland','Honest Grover',1885,1889,'Democrat','New Jersey',1837,1908,'Caldwell, New Jersey',ARRAY['Thomas A. Hendricks'],16,'gilded_age','The only president to serve two non-consecutive terms — first half.','A man is known by the company he keeps, and also by the company from which he is kept.',ARRAY['First Democrat elected president since before the Civil War','Vetoed hundreds of private pension bills','Signed the Interstate Commerce Act','Married in the White House — the only president to do so','Fought political corruption throughout his career'],'His landslide veto record — vetoing more bills than all previous presidents combined.','Cleveland married 21-year-old Frances Folsom in the White House in 1886, a 28-year age gap that scandalized some and delighted others.'),
(23,'Benjamin Harrison','Benjamin','Harrison','Little Ben',1889,1893,'Republican','Indiana',1833,1901,'North Bend, Ohio',ARRAY['Levi P. Morton'],29,'gilded_age','Grandson of a president. Father of six new states.','We cannot afford in America to have any discontented classes.',ARRAY['Admitted six new states to the Union','Signed the Sherman Antitrust Act','Signed the Sherman Silver Purchase Act','Established the modern Navy','Signed the McKinley Tariff raising import duties'],'The admission of six states in just 16 months — North Dakota, South Dakota, Montana, Washington, Idaho, and Wyoming.','Harrison lost the popular vote to Cleveland in 1888 but won the Electoral College. Electric lights were installed in the White House during his term but he and his wife refused to touch the switches.'),
(24,'Grover Cleveland','Grover','Cleveland','Honest Grover',1893,1897,'Democrat','New Jersey',1837,1908,'Caldwell, New Jersey',ARRAY['Adlai Stevenson I'],16,'gilded_age','Came back for a second act. Faced a worse economy.','Officeholders are the agents of the people, not their masters.',ARRAY['Handled the Panic of 1893','Repealed the Sherman Silver Purchase Act','Sent federal troops to end the Pullman Strike','Refused to annex Hawaii after the overthrow of Queen Liliuokalani','Maintained the gold standard'],'Sending federal troops to break the Pullman Strike of 1894, establishing federal authority in labor disputes.','Cleveland is counted as both the 22nd and 24th president. He underwent secret surgery for oral cancer on a yacht in 1893 to avoid public panic.'),
(25,'William McKinley','William','McKinley','Idol of Ohio',1897,1901,'Republican','Ohio',1843,1901,'Niles, Ohio',ARRAY['Garret Hobart','Theodore Roosevelt'],15,'gilded_age','Built an empire. Paid with his life.','That''s all a man can hope for during his lifetime — to set an example — and when he is dead, to be an inspiration for history.',ARRAY['Won the Spanish-American War acquiring Guam, Puerto Rico, and the Philippines','Annexed Hawaii','Raised the tariff protecting American industry','Restored economic prosperity after the Panic of 1893','Opened trade with China via the Open Door Policy'],'The Spanish-American War of 1898, transforming the United States into a global imperial power in just four months.','McKinley always wore a red carnation as a good luck charm. He gave it to a little girl moments before being shot at the Buffalo Pan-American Exposition.'),
(26,'Theodore Roosevelt','Theodore','Roosevelt','TR',1901,1909,'Republican','New York',1858,1919,'New York City, New York',ARRAY['Charles W. Fairbanks'],4,'progressive','The Rough Rider who charged into the presidency and never stopped moving.','Do what you can, with what you have, where you are.',ARRAY['Broke up corporate monopolies through trust-busting','Built the Panama Canal','Won the Nobel Peace Prize for ending the Russo-Japanese War','Established 150 national forests and 5 national parks','Launched the Square Deal domestic program'],'The Panama Canal — negotiating and pushing through construction of one of history''s greatest infrastructure projects.','The Teddy Bear was named after Roosevelt after he refused to shoot a captured bear on a hunting trip. He was also blind in one eye from a White House boxing match.'),
(27,'William Howard Taft','William Howard','Taft','Big Bill',1909,1913,'Republican','Ohio',1857,1930,'Cincinnati, Ohio',ARRAY['James S. Sherman'],24,'progressive','Filed more antitrust suits than TR. Got none of the credit.','Don''t write so that you can be understood, write so that you can''t be misunderstood.',ARRAY['Filed more antitrust suits than Roosevelt in fewer years','Established the parcel post system','Signed the 16th Amendment authorizing the income tax','Later served as Chief Justice of the Supreme Court','Created the Commerce and Labor departments split'],'Being the only person to serve as both President and Chief Justice — and by his own account preferring the latter.','Taft is often said to have gotten stuck in the White House bathtub. At 6 foot 2 and over 300 pounds, he was the heaviest president.'),
(28,'Woodrow Wilson','Woodrow','Wilson','The Professor',1913,1921,'Democrat','Virginia',1856,1924,'Staunton, Virginia',ARRAY['Thomas R. Marshall'],11,'progressive','Idealist who reshaped the world. Couldn''t change the Senate.','The history of liberty is a history of resistance.',ARRAY['Led the United States through World War I','Proposed the 14 Points and the League of Nations','Signed the Federal Reserve Act','Passed the Clayton Antitrust Act','Saw the 19th Amendment ratified granting women the vote'],'The Treaty of Versailles and the fight for the League of Nations — winning the Nobel Peace Prize then watching the Senate reject it while suffering a debilitating stroke.','Wilson suffered a massive stroke in 1919 that left him incapacitated. His wife Edith effectively managed presidential affairs, leading some to call her the first female president.'),
(29,'Warren G. Harding','Warren','Harding','Wobbly Warren',1921,1923,'Republican','Ohio',1865,1923,'Blooming Grove, Ohio',ARRAY['Calvin Coolidge'],38,'new_deal','The most popular president of his time. The most corrupt.','My friends, my goddamned friends, they''re the ones who keep me walking the floor at nights.',ARRAY['Ended World War I formally with the Treaty of Berlin','Convened the Washington Naval Conference on arms limitations','Restored economic prosperity after Wilson era','Created the Bureau of the Budget','Released political prisoners jailed under Wilson'],'The Teapot Dome scandal, the most significant government corruption scandal before Watergate, in which his Interior Secretary leased federal oil reserves for bribes.','Harding was the first president to speak on radio and the first to have his voice recorded.'),
(30,'Calvin Coolidge','Calvin','Coolidge','Silent Cal',1923,1929,'Republican','Vermont',1872,1933,'Plymouth Notch, Vermont',ARRAY['Charles G. Dawes'],27,'new_deal','Said little. Did less. Watched the good times roll toward disaster.','Nothing in this world can take the place of persistence.',ARRAY['Restored confidence after the Harding scandals','Signed the Immigration Act of 1924','Presided over the Roaring Twenties prosperity','Signed the Indian Citizenship Act granting citizenship to Native Americans','Reduced the national debt and cut taxes'],'Choosing not to run in 1928, leaving before the Great Depression that his policies helped create.','Coolidge was so terse a dinner guest bet she could get him to say more than two words. "You lose," he replied. He also kept a pet raccoon named Rebecca who walked on a leash around the White House.');

INSERT INTO presidents (number, name, first_name, last_name, nickname, term_start, term_end, party, home_state, birth_year, death_year, birth_place, vice_presidents, historian_ranking, era, tagline, famous_quote, key_achievements, defining_moment, did_you_know) VALUES
(31,'Herbert Hoover','Herbert','Hoover','The Great Engineer',1929,1933,'Republican','Iowa',1874,1964,'West Branch, Iowa',ARRAY['Charles Curtis'],36,'new_deal','Great humanitarian. Great engineer. Wrong man for the Depression.','Older men declare war. But it is the youth that must fight and die.',ARRAY['Coordinated massive European food relief after World War I','Modernized the Commerce Department','Signed the Smoot-Hawley Tariff','Established the Reconstruction Finance Corporation','Created the Veterans Administration'],'The Great Depression beginning with the 1929 stock market crash, which Hoover failed to address through direct federal relief, leading to Hoovervilles and catastrophic electoral defeat.','Before becoming president, Hoover coordinated food relief for 10 million starving Belgians during World War I. He spoke fluent Mandarin Chinese.'),
(32,'Franklin D. Roosevelt','Franklin','Roosevelt','FDR',1933,1945,'Democrat','New York',1882,1945,'Hyde Park, New York',ARRAY['John Nance Garner','Henry A. Wallace','Harry S. Truman'],3,'new_deal','New Deal. WWII. Four terms. The president who remade America.','The only thing we have to fear is fear itself.',ARRAY['Led the U.S. through the Great Depression with the New Deal','Led the Allied coalition to victory in World War II','Established Social Security','Served an unprecedented four terms','Created dozens of federal agencies still operating today'],'Delivering the First Inaugural Address on March 4, 1933, telling a nation in economic freefall that the only thing we have to fear is fear itself.','FDR was paralyzed from the waist down by polio but worked to conceal his disability — there are fewer than four photographs of him in a wheelchair.'),
(33,'Harry S. Truman','Harry','Truman','Give ''Em Hell Harry',1945,1953,'Democrat','Missouri',1884,1972,'Lamar, Missouri',ARRAY['Alben W. Barkley'],6,'new_deal','Nobody expected much. He changed everything.','The buck stops here.',ARRAY['Made the decision to drop atomic bombs on Japan ending World War II','Implemented the Marshall Plan rebuilding Western Europe','Established NATO','Desegregated the U.S. military by executive order','Recognized the State of Israel within minutes of its declaration'],'The decision to drop atomic bombs on Hiroshima and Nagasaki, ending World War II and ushering in the nuclear age.','Truman''s middle name was literally just "S" — it stood for nothing, a compromise between his two grandfathers whose names both started with S.'),
(34,'Dwight D. Eisenhower','Dwight','Eisenhower','Ike',1953,1961,'Republican','Kansas',1890,1969,'Denison, Texas',ARRAY['Richard Nixon'],5,'cold_war','Won WWII. Built the highway system. Warned about the military-industrial complex.','We must guard against the acquisition of unwarranted influence by the military-industrial complex.',ARRAY['Ended the Korean War','Built the Interstate Highway System','Created NASA','Sent troops to desegregate Little Rock schools','Warned against the military-industrial complex in his farewell address'],'His farewell address warning the nation about the military-industrial complex — a speech that proved prophetic and is considered one of the most important of the 20th century.','Eisenhower was an accomplished oil painter who completed over 260 paintings after leaving office.'),
(35,'John F. Kennedy','John','Kennedy','JFK',1961,1963,'Democrat','Massachusetts',1917,1963,'Brookline, Massachusetts',ARRAY['Lyndon B. Johnson'],8,'cold_war','Ask not. Go to the moon. Cut down in Dallas.','Ask not what your country can do for you — ask what you can do for your country.',ARRAY['Resolved the Cuban Missile Crisis without nuclear war','Committed the nation to landing on the moon','Founded the Peace Corps','Signed the Nuclear Test Ban Treaty','Advanced civil rights legislation later passed by LBJ'],'The Cuban Missile Crisis of October 1962 — thirteen days that brought the world closer to nuclear war than at any other point in history.','Kennedy was the youngest person elected president at age 43 and the first Catholic president. He donated his entire presidential salary to charity.'),
(36,'Lyndon B. Johnson','Lyndon','Johnson','LBJ',1963,1969,'Democrat','Texas',1908,1973,'Stonewall, Texas',ARRAY['Hubert Humphrey'],10,'cold_war','Great Society at home. Vietnam abroad. Too much of both.','Yesterday is not ours to recover, but tomorrow is ours to win or lose.',ARRAY['Signed the Civil Rights Act of 1964','Signed the Voting Rights Act of 1965','Created Medicare and Medicaid','Launched the War on Poverty and Great Society programs','Signed the Immigration and Nationality Act of 1965'],'Signing the Civil Rights Act of 1964 — a Southern Democrat dismantling institutional segregation, telling an aide "We have lost the South for a generation."','LBJ conducted meetings while sitting on the toilet and was famous for the Johnson Treatment — getting inches from people''s faces to persuade them.'),
(37,'Richard Nixon','Richard','Nixon','Tricky Dick',1969,1974,'Republican','California',1913,1994,'Yorba Linda, California',ARRAY['Spiro Agnew','Gerald Ford'],26,'cold_war','Opened China. Ended Vietnam. Destroyed himself.','I am not a crook.',ARRAY['Opened diplomatic relations with China','Signed SALT I nuclear arms limitation treaty','Ended American combat in Vietnam','Established the EPA','Was the first and only president to resign from office'],'The Watergate scandal and his resignation on August 9, 1974 — the first and only presidential resignation in U.S. history.','Nixon was a gifted pianist who appeared on The Jack Paar Tonight Show. He used poker winnings from his Navy days to fund his first congressional campaign.'),
(38,'Gerald Ford','Gerald','Ford','Jerry',1974,1977,'Republican','Nebraska',1913,2006,'Omaha, Nebraska',ARRAY['Nelson Rockefeller'],28,'cold_war','Nobody elected him. Nobody blamed him — except for the pardon.','Our long national nightmare is over.',ARRAY['Assumed presidency after Nixon resignation restoring stability','Pardoned Nixon ending Watergate crisis','Signed the Helsinki Accords on human rights','Evacuated Americans from Saigon','Survived two assassination attempts in 17 days'],'The pardon of Richard Nixon on September 8, 1974 — a decision that likely cost Ford the 1976 election but which historians have increasingly vindicated.','Ford is the only person to serve as both Vice President and President without being elected to either office. He was also offered NFL contracts by both the Detroit Lions and Green Bay Packers.'),
(39,'Jimmy Carter','Jimmy','Carter','Jimmy',1977,1981,'Democrat','Georgia',1924,2024,'Plains, Georgia',ARRAY['Walter Mondale'],22,'modern','Best ex-president in history. The presidency was a harder fit.','We must adjust to changing times and still hold to unchanging principles.',ARRAY['Brokered the Camp David Accords between Israel and Egypt','Created the Department of Energy and Education','Negotiated the Panama Canal Treaties','Championed human rights as foreign policy','Won the Nobel Peace Prize in 2002 for post-presidential work'],'The Camp David Accords of 1978, personally mediating 13 days of secret negotiations producing the only lasting peace treaty between Israel and an Arab nation.','Carter is the longest-lived president, dying at age 100 in 2024. After leaving the White House he built houses with Habitat for Humanity and taught Sunday school well into his 90s.'),
(40,'Ronald Reagan','Ronald','Reagan','The Gipper',1981,1989,'Republican','Illinois',1911,2004,'Tampico, Illinois',ARRAY['George H.W. Bush'],9,'modern','Morning in America. The Great Communicator. The end of the Cold War.','Mr. Gorbachev, tear down this wall!',ARRAY['Rebuilt the U.S. economy through Reaganomics tax cuts','Escalated Cold War pressure contributing to Soviet collapse','Negotiated the INF Treaty with Gorbachev','Survived an assassination attempt 69 days into office','Appointed the first female Supreme Court Justice Sandra Day O''Connor'],'Standing at the Brandenburg Gate in 1987 demanding "Mr. Gorbachev, tear down this wall!" — dismissed by skeptics, it became the defining image of the Cold War''s end.','Reagan was the oldest person elected president at 69 and a lifeguard in his youth who saved 77 people from drowning in the Rock River in Illinois.');

INSERT INTO presidents (number, name, first_name, last_name, nickname, term_start, term_end, party, home_state, birth_year, death_year, birth_place, vice_presidents, historian_ranking, era, tagline, famous_quote, key_achievements, defining_moment, did_you_know) VALUES
(41,'George H.W. Bush','George Herbert Walker','Bush','Poppy',1989,1993,'Republican','Massachusetts',1924,2018,'Milton, Massachusetts',ARRAY['Dan Quayle'],21,'modern','Won the Cold War. Won the Gulf War. Lost the election to the economy.','Read my lips: no new taxes.',ARRAY['Managed the peaceful end of the Cold War and German reunification','Led the Gulf War coalition liberating Kuwait','Signed the Americans with Disabilities Act','Negotiated NAFTA','Signed the Clean Air Act Amendments'],'Managing the peaceful dissolution of the Soviet Union and German reunification — the most consequential geopolitical transformation since World War II without firing a shot.','Bush was the last World War II veteran to serve as president. He celebrated his 75th, 80th, 85th, and 90th birthdays by skydiving.'),
(42,'Bill Clinton','Bill','Clinton','Slick Willie',1993,2001,'Democrat','Arkansas',1946,NULL,'Hope, Arkansas',ARRAY['Al Gore'],19,'modern','Economic boom. Personal scandal. The first president of the internet age.','There is nothing wrong with America that cannot be cured by what is right with America.',ARRAY['Balanced the federal budget and created a surplus','Signed NAFTA and supported globalization','Expanded NATO eastward','Brokered the Good Friday Agreement in Northern Ireland','Was impeached by the House but acquitted by the Senate'],'His impeachment in 1998, surviving to finish his term with a 65% approval rating — the highest end-of-term rating since FDR.','Clinton was a Rhodes Scholar at Oxford and played the saxophone on The Arsenio Hall Show during the 1992 campaign.'),
(43,'George W. Bush','George Walker','Bush','Dubya',2001,2009,'Republican','Connecticut',1946,NULL,'New Haven, Connecticut',ARRAY['Dick Cheney'],30,'modern','9/11. Iraq. The defining presidency of the terror age.','Either you are with us, or you are with the terrorists.',ARRAY['Led the nation''s response to the September 11 attacks','Launched the War on Terror and invaded Afghanistan','Created the Department of Homeland Security','Signed PEPFAR saving millions of lives in Africa','Passed No Child Left Behind education reform'],'Standing on the rubble of the World Trade Center with a bullhorn three days after 9/11, declaring the people who knocked these buildings down will hear all of us soon.','Bush is an accomplished oil painter who has created hundreds of portraits of world leaders and veterans. He gave all profits from his book to veterans'' charities.'),
(44,'Barack Obama','Barack','Obama','No Drama Obama',2009,2017,'Democrat','Hawaii',1961,NULL,'Honolulu, Hawaii',ARRAY['Joe Biden'],12,'modern','Yes We Can. The first. The hope. The long game.','We are the change that we seek.',ARRAY['First African American president','Signed the Affordable Care Act expanding health coverage','Ordered the operation that killed Osama bin Laden','Led the economic recovery from the Great Recession','Signed the Paris Climate Agreement'],'His election on November 4, 2008 as the first African American president — a moment millions who had lived through segregation never expected to see.','Obama won the Nobel Peace Prize less than nine months into his first term. He is left-handed and was a constitutional law professor at the University of Chicago.'),
(45,'Donald Trump','Donald','Trump','The Donald',2017,2021,'Republican','New York',1946,NULL,'Queens, New York',ARRAY['Mike Pence'],NULL,'current','Disrupted everything. Changed American politics forever.','Make America Great Again.',ARRAY['Signed the Tax Cuts and Jobs Act','Brokered the Abraham Accords normalizing Israel-Arab relations','Appointed three Supreme Court justices','Negotiated the USMCA replacing NAFTA','Was impeached twice by the House'],'Becoming the first president to be impeached twice — first for his Ukraine phone call in 2019, and again for incitement of insurrection following January 6, 2021.','Trump is the first president with no prior military or government service. He was also the oldest person elected president for the first time at age 70 in 2016.'),
(46,'Joe Biden','Joe','Biden','Scranton Joe',2021,2025,'Democrat','Pennsylvania',1942,NULL,'Scranton, Pennsylvania',ARRAY['Kamala Harris'],NULL,'current','Saved democracy. Passed the big bills. Stepped aside.','There is nothing beyond our capacity. We are the United States of America.',ARRAY['Passed the Bipartisan Infrastructure Law','Signed the Inflation Reduction Act addressing climate change','Led Western support for Ukraine against Russian invasion','Signed the CHIPS Act boosting American semiconductor manufacturing','Oversaw historic job creation and economic recovery post-COVID'],'Choosing not to seek re-election in July 2024, stepping aside to allow a new generation of Democratic leadership.','Biden overcame a severe stutter as a child by memorizing and reciting poetry in the mirror. He commuted by Amtrak from Delaware to Washington daily for 36 years as a senator.');

-- Wire up preceded_by / succeeded_by
UPDATE presidents SET preceded_by = NULL, succeeded_by = 2 WHERE number = 1;
UPDATE presidents SET preceded_by = 1, succeeded_by = 3 WHERE number = 2;
UPDATE presidents SET preceded_by = 2, succeeded_by = 4 WHERE number = 3;
UPDATE presidents SET preceded_by = 3, succeeded_by = 5 WHERE number = 4;
UPDATE presidents SET preceded_by = 4, succeeded_by = 6 WHERE number = 5;
UPDATE presidents SET preceded_by = 5, succeeded_by = 7 WHERE number = 6;
UPDATE presidents SET preceded_by = 6, succeeded_by = 8 WHERE number = 7;
UPDATE presidents SET preceded_by = 7, succeeded_by = 9 WHERE number = 8;
UPDATE presidents SET preceded_by = 8, succeeded_by = 10 WHERE number = 9;
UPDATE presidents SET preceded_by = 9, succeeded_by = 11 WHERE number = 10;
UPDATE presidents SET preceded_by = 10, succeeded_by = 12 WHERE number = 11;
UPDATE presidents SET preceded_by = 11, succeeded_by = 13 WHERE number = 12;
UPDATE presidents SET preceded_by = 12, succeeded_by = 14 WHERE number = 13;
UPDATE presidents SET preceded_by = 13, succeeded_by = 15 WHERE number = 14;
UPDATE presidents SET preceded_by = 14, succeeded_by = 16 WHERE number = 15;
UPDATE presidents SET preceded_by = 15, succeeded_by = 17 WHERE number = 16;
UPDATE presidents SET preceded_by = 16, succeeded_by = 18 WHERE number = 17;
UPDATE presidents SET preceded_by = 17, succeeded_by = 19 WHERE number = 18;
UPDATE presidents SET preceded_by = 18, succeeded_by = 20 WHERE number = 19;
UPDATE presidents SET preceded_by = 19, succeeded_by = 21 WHERE number = 20;
UPDATE presidents SET preceded_by = 20, succeeded_by = 22 WHERE number = 21;
UPDATE presidents SET preceded_by = 21, succeeded_by = 23 WHERE number = 22;
UPDATE presidents SET preceded_by = 22, succeeded_by = 24 WHERE number = 23;
UPDATE presidents SET preceded_by = 23, succeeded_by = 25 WHERE number = 24;
UPDATE presidents SET preceded_by = 24, succeeded_by = 26 WHERE number = 25;
UPDATE presidents SET preceded_by = 25, succeeded_by = 27 WHERE number = 26;
UPDATE presidents SET preceded_by = 26, succeeded_by = 28 WHERE number = 27;
UPDATE presidents SET preceded_by = 27, succeeded_by = 29 WHERE number = 28;
UPDATE presidents SET preceded_by = 28, succeeded_by = 30 WHERE number = 29;
UPDATE presidents SET preceded_by = 29, succeeded_by = 31 WHERE number = 30;
UPDATE presidents SET preceded_by = 30, succeeded_by = 32 WHERE number = 31;
UPDATE presidents SET preceded_by = 31, succeeded_by = 33 WHERE number = 32;
UPDATE presidents SET preceded_by = 32, succeeded_by = 34 WHERE number = 33;
UPDATE presidents SET preceded_by = 33, succeeded_by = 35 WHERE number = 34;
UPDATE presidents SET preceded_by = 34, succeeded_by = 36 WHERE number = 35;
UPDATE presidents SET preceded_by = 35, succeeded_by = 37 WHERE number = 36;
UPDATE presidents SET preceded_by = 36, succeeded_by = 38 WHERE number = 37;
UPDATE presidents SET preceded_by = 37, succeeded_by = 39 WHERE number = 38;
UPDATE presidents SET preceded_by = 38, succeeded_by = 40 WHERE number = 39;
UPDATE presidents SET preceded_by = 39, succeeded_by = 41 WHERE number = 40;
UPDATE presidents SET preceded_by = 40, succeeded_by = 42 WHERE number = 41;
UPDATE presidents SET preceded_by = 41, succeeded_by = 43 WHERE number = 42;
UPDATE presidents SET preceded_by = 42, succeeded_by = 44 WHERE number = 43;
UPDATE presidents SET preceded_by = 43, succeeded_by = 45 WHERE number = 44;
UPDATE presidents SET preceded_by = 44, succeeded_by = 46 WHERE number = 45;
UPDATE presidents SET preceded_by = 45, succeeded_by = NULL WHERE number = 46;
